import type { Finding, Investigation, ScanResults } from '@/api/types'
import { PILLAR_LABELS, type PillarKey } from '@/api/types'
import { absoluteTime, displayTool, findingLocation, grade, repoLabel, scoreVerdict, severityCounts } from '@/lib/format'

function download(filename: string, contents: string, mime: string) {
  const blob = new Blob([contents], { type: `${mime};charset=utf-8` })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

function slug(results: ScanResults) {
  return `kovr-${repoLabel(results.repo_url).replace(/[^\w.-]+/g, '-')}-${results.scan_id.slice(0, 8)}`
}

function pillarLabel(pillar: string) {
  return PILLAR_LABELS[pillar as PillarKey] ?? pillar
}

export function exportJson(results: ScanResults) {
  const payload = {
    generator: 'KOVR AI Security Scanner',
    generatedAt: new Date().toISOString(),
    scan: {
      scan_id: results.scan_id,
      repo_url: results.repo_url,
      score: results.score,
      grade: grade(results.score),
      verdict: scoreVerdict(results.score),
    },
    summary: severityCounts(results.findings),
    findings: results.findings,
  }
  download(`${slug(results)}.json`, JSON.stringify(payload, null, 2), 'application/json')
}

export function exportCsv(results: ScanResults) {
  const escape = (value: unknown) => `"${String(value ?? '').replace(/"/g, '""')}"`
  const header = ['id', 'severity', 'pillar', 'tool', 'title', 'file', 'line', 'verified', 'description']
  const rows = results.findings.map((f) =>
    [f.id, f.severity, f.pillar, f.tool, f.title, f.file, f.line ?? '', f.verified ?? 'open', f.description]
      .map(escape)
      .join(','),
  )
  download(`${slug(results)}.csv`, [header.join(','), ...rows].join('\n'), 'text/csv')
}

export function exportMarkdown(results: ScanResults, investigations: Record<string, Investigation> = {}) {
  const counts = severityCounts(results.findings)
  const open = results.findings.filter((f) => f.verified !== 'resolved')
  const resolved = results.findings.length - open.length

  const lines: string[] = [
    `# Security Analysis Report — ${repoLabel(results.repo_url)}`,
    '',
    `**Scan** \`${results.scan_id}\``,
    `**Repository** ${results.repo_url}`,
    `**Generated** ${absoluteTime(new Date().toISOString())}`,
    '',
    `## Score: ${results.score}/100 (${grade(results.score)}) — ${scoreVerdict(results.score)}`,
    '',
    `${resolved} of ${results.findings.length} findings resolved · ${open.length} still open.`,
    '',
    '| Severity | Count |',
    '| --- | --- |',
    ...(Object.keys(counts) as (keyof typeof counts)[])
      .filter((key) => counts[key] > 0)
      .map((key) => `| ${key} | ${counts[key]} |`),
    '',
    '## Findings',
    '',
  ]

  const section = (finding: Finding) => {
    const investigation = investigations[finding.id]
    lines.push(
      `### [${(finding.severity ?? 'unknown').toUpperCase()}] ${finding.title}`,
      '',
      `- **Location:** \`${findingLocation(finding)}\``,
      `- **Pillar:** ${pillarLabel(finding.pillar)}${displayTool(finding.tool) ? ` · **Tool:** ${displayTool(finding.tool)}` : ''}`,
      `- **Status:** ${finding.verified === 'resolved' ? 'resolved' : 'open'}`,
      '',
      finding.description || '',
      '',
    )

    const rootCause = investigation?.root_cause ?? finding.root_cause
    const impact = investigation?.impact ?? finding.impact
    if (rootCause) lines.push(`**Root cause.** ${rootCause}`, '')
    if (impact) lines.push(`**Impact.** ${impact}`, '')
    if (investigation?.attack_path) lines.push(`**Attack path.** ${investigation.attack_path}`, '')
    if (investigation?.fix_explanation) lines.push(`**Suggested fix.** ${investigation.fix_explanation}`, '')
    if (investigation?.before_code?.trim() && investigation?.after_code?.trim()) {
      lines.push(
        '```diff',
        ...investigation.before_code.split('\n').map((line) => `-${line}`),
        ...investigation.after_code.split('\n').map((line) => `+${line}`),
        '```',
        '',
      )
    }
  }

  for (const finding of open) section(finding)

  if (resolved > 0) {
    lines.push('## Resolved', '')
    for (const finding of results.findings.filter((f) => f.verified === 'resolved')) section(finding)
  }

  lines.push('---', '', 'Generated by KOVR.')
  download(`${slug(results)}.md`, lines.join('\n'), 'text/markdown')
}

/** Hands the report to the browser's own print pipeline. */
export function exportPdf() {
  window.print()
}
